[workspace]
members = ["proc_macros"]

[package]
name = "brocolib"
version = "0.1.0"
authors = ["StackDoubleFlow <ojaslandge@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
# We need to be able to read the codegen data which takes time
opt-level = 1

[dependencies]
bad64 = "0.6"
bad64-sys = "0.5"
anyhow = "1.0"
clap = "3"
object = "0.28"
petgraph = "0.6"
byteorder = "1.4"
# id-arena = "2.2"
thiserror = "1"
brocolib_proc_macros = { path = "./proc_macros"}